### ISSUE TITLE
Домашка №3 (ООП)

### ISSUE THREAD

**Issue by kottans-net** [maksim36ua/KottansHomework#4]
Предлагаем вам выполнить домашку по ООП https://github.com/Zaknafeyn/OOP.Task

**Comment by maksim36ua** [comment]
Finished homework #3 (https://github.com/maksim36ua/KottansHomework/tree/master/homework_3)

**Comment by kottans-net** [comment]
Проверено

Замечания:
- метод Move дублируется - лучше вынести его в базовый класс (ShapeBase)
- для свойства ShapeName можно использовать новый синтаксис C#: public override string ShapeName =>  "Rectangle"; 
- лишняя переменная Perimeter в классе Triangle
